#!/usr/bin/env python3
"""Squintless scheme generator.

Single source of truth: palettes/<variant>.json. From each palette this renders
every per-terminal color scheme into config/generated/**, (re)writes the two
Windows Terminal scheme files to their existing config/ paths (so the live
installer/one-liner is untouched), and emits a computed WCAG contrast table.

Stdlib only (json, plistlib, pathlib) -- no pip install, runs anywhere Python 3
runs. All files are written as bytes with LF newlines for deterministic,
cross-platform, diff-stable output.

Usage:
  python tools/gen.py            # write all generated files
  python tools/gen.py --check    # exit 1 if any generated file is stale (CI)
"""
from __future__ import annotations

import json
import plistlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTES = ROOT / "palettes"

# ANSI 0..15 in the canonical order every terminal expects.
NORMAL = ["black", "red", "green", "yellow", "blue", "purple", "cyan", "white"]
BRIGHT = ["brightBlack", "brightRed", "brightGreen", "brightYellow",
          "brightBlue", "brightPurple", "brightCyan", "brightWhite"]
ANSI16 = NORMAL + BRIGHT

GEN = "config/generated"
BANNER = "generated by tools/gen.py -- edit palettes/*.json, then re-run; do not hand-edit"


# ---------- color helpers ----------
def rgb01(hex_str):
    h = hex_str.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def _chan(c):
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_str):
    r, g, b = (_chan(c) for c in rgb01(hex_str))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(h1, h2):
    l1, l2 = luminance(h1), luminance(h2)
    hi, lo = max(l1, l2), min(l1, l2)
    return (hi + 0.05) / (lo + 0.05)


def wcag_rating(ratio):
    if ratio >= 7.0:
        return "AAA"
    if ratio >= 4.5:
        return "AA"
    if ratio >= 3.0:
        return "AA (large/UI)"
    return "below 3:1"


# ---------- per-format emitters (return str unless noted) ----------
def wt_scheme_dict(p):
    c = p["colors"]
    d = {"name": p["scheme_name"], "background": c["background"], "foreground": c["foreground"]}
    for k in ANSI16:
        d[k] = c[k]
    d["cursorColor"] = c["cursor"]
    d["selectionBackground"] = c["selection_background"]
    return d


def emit_wt_scheme(p):
    return json.dumps(wt_scheme_dict(p), indent=2) + "\n"


def emit_wt_fragment(p):
    frag = {"$schema": "https://aka.ms/terminal-profiles-schema", "schemes": [wt_scheme_dict(p)]}
    return json.dumps(frag, indent=2) + "\n"


def emit_kitty(p):
    c = p["colors"]
    out = [f"# {p['scheme_name']} -- {BANNER}",
           f"foreground {c['foreground']}",
           f"background {c['background']}",
           f"cursor {c['cursor']}",
           f"cursor_text_color {c['background']}",
           f"selection_foreground {c['foreground']}",
           f"selection_background {c['selection_background']}"]
    for i, name in enumerate(ANSI16):
        out.append(f"color{i} {c[name]}")
    return "\n".join(out) + "\n"


def emit_alacritty(p):
    c = p["colors"]
    def block(title, mapping):
        lines = [f"[colors.{title}]"]
        for k, v in mapping.items():
            lines.append(f'{k} = "{v}"')
        return "\n".join(lines)
    def alac(keys):  # alacritty names our 'purple' slot 'magenta'; bright lives in its own table
        out = {}
        for k in keys:
            name = "magenta" if k.lower().endswith("purple") else k.replace("bright", "").lower()
            out[name] = c[k]
        return out
    normal, bright = alac(NORMAL), alac(BRIGHT)
    parts = [f"# {p['scheme_name']} -- {BANNER}",
             block("primary", {"background": c["background"], "foreground": c["foreground"]}),
             block("cursor", {"cursor": c["cursor"], "text": c["background"]}),
             block("selection", {"background": c["selection_background"], "text": c["foreground"]}),
             block("normal", normal),
             block("bright", bright)]
    return "\n\n".join(parts) + "\n"


def emit_wezterm(p):
    c = p["colors"]
    ansi = ", ".join(f'"{c[k]}"' for k in NORMAL)
    brights = ", ".join(f'"{c[k]}"' for k in BRIGHT)
    return (f"# {p['scheme_name']} -- {BANNER}\n"
            "[colors]\n"
            f'foreground = "{c["foreground"]}"\n'
            f'background = "{c["background"]}"\n'
            f'cursor_bg = "{c["cursor"]}"\n'
            f'cursor_border = "{c["cursor"]}"\n'
            f'cursor_fg = "{c["background"]}"\n'
            f'selection_bg = "{c["selection_background"]}"\n'
            f'selection_fg = "{c["foreground"]}"\n'
            f"ansi = [{ansi}]\n"
            f"brights = [{brights}]\n\n"
            "[metadata]\n"
            f'name = "{p["scheme_name"]}"\n'
            f'author = "{p.get("author", "Sameer Zahir")}"\n')


def emit_ghostty(p):
    c = p["colors"]
    out = [f"# {p['scheme_name']} -- {BANNER}",
           f"background = {c['background']}",
           f"foreground = {c['foreground']}",
           f"cursor-color = {c['cursor']}",
           f"selection-background = {c['selection_background']}",
           f"selection-foreground = {c['background']}"]
    for i, name in enumerate(ANSI16):
        out.append(f"palette = {i}={c[name]}")
    return "\n".join(out) + "\n"


def emit_xresources(p):
    c = p["colors"]
    out = [f"! {p['scheme_name']} -- {BANNER}",
           f"*.foreground: {c['foreground']}",
           f"*.background: {c['background']}",
           f"*.cursorColor: {c['cursor']}"]
    for i, name in enumerate(ANSI16):
        out.append(f"*.color{i}: {c[name]}")
    return "\n".join(out) + "\n"


def emit_iterm2(p):
    """iTerm2 .itermcolors is an Apple plist; plistlib renders it exactly."""
    c = p["colors"]
    def comp(hex_str):
        r, g, b = rgb01(hex_str)
        return {"Color Space": "sRGB", "Red Component": r, "Green Component": g,
                "Blue Component": b, "Alpha Component": 1.0}
    d = {}
    for i, name in enumerate(ANSI16):
        d[f"Ansi {i} Color"] = comp(c[name])
    d["Background Color"] = comp(c["background"])
    d["Foreground Color"] = comp(c["foreground"])
    d["Cursor Color"] = comp(c["cursor"])
    d["Cursor Text Color"] = comp(c["foreground"])
    d["Selection Color"] = comp(c["selection_background"])
    d["Selected Text Color"] = comp(c["foreground"])
    return plistlib.dumps(d, sort_keys=True)  # bytes


def emit_wcag(palettes):
    rows = ["# WCAG contrast ratios",
            "",
            f"<!-- {BANNER} -->",
            "",
            "Foreground and each accent color measured against the scheme background.",
            "AAA >= 7:1, AA >= 4.5:1, AA (large/UI) >= 3:1 (WCAG 2.x).",
            ""]
    accents = ["foreground", "red", "green", "yellow", "blue", "purple", "cyan", "white", "brightBlack"]
    for p in palettes:
        c = p["colors"]
        bg = c["background"]
        rows.append(f"## {p['scheme_name']} — on `{bg}`")
        rows.append("")
        rows.append("| Role | Hex | Contrast | WCAG |")
        rows.append("| --- | --- | --- | --- |")
        for role in accents:
            hexv = c[role]
            ratio = contrast(hexv, bg)
            rows.append(f"| {role} | `{hexv}` | {ratio:.2f}:1 | {wcag_rating(ratio)} |")
        rows.append("")
    return "\n".join(rows) + "\n"


# ---------- assembly ----------
def build_outputs():
    """Return {relative_path: bytes} for every generated artifact."""
    palettes = {}
    for f in sorted(PALETTES.glob("*.json")):
        p = json.loads(f.read_text(encoding="utf-8"))
        palettes[p["variant"]] = p
    if set(palettes) != {"light", "dark"}:
        raise SystemExit(f"expected light+dark palettes, found: {sorted(palettes)}")

    out = {}

    def add(rel, content):
        out[rel] = content if isinstance(content, bytes) else content.encode("utf-8")

    for variant, p in palettes.items():
        sfx = "" if variant == "light" else ".dark"  # back-compat: light is unsuffixed
        gsfx = variant  # generated files use explicit light/dark
        # Back-compat Windows scheme files at their existing config/ paths:
        add(f"config/windows-terminal.scheme{sfx}.json", emit_wt_scheme(p))
        # Generated per-terminal artifacts:
        add(f"{GEN}/windows/squintless-{gsfx}.fragment.json", emit_wt_fragment(p))
        add(f"{GEN}/kitty/squintless-{gsfx}.conf", emit_kitty(p))
        add(f"{GEN}/alacritty/squintless-{gsfx}.toml", emit_alacritty(p))
        add(f"{GEN}/wezterm/squintless-{gsfx}.toml", emit_wezterm(p))
        add(f"{GEN}/ghostty/squintless-{gsfx}", emit_ghostty(p))
        add(f"{GEN}/xresources/squintless-{gsfx}.Xresources", emit_xresources(p))
        add(f"{GEN}/iterm2/squintless-{gsfx}.itermcolors", emit_iterm2(p))

    # Ordered light-then-dark for the WCAG doc.
    ordered = [palettes["light"], palettes["dark"]]
    add(f"{GEN}/wcag-contrast.md", emit_wcag(ordered))
    return out


def main(argv):
    check = "--check" in argv
    outputs = build_outputs()
    stale = []
    for rel, content in sorted(outputs.items()):
        path = ROOT / rel
        if check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    if check:
        if stale:
            print("STALE generated files (run `python tools/gen.py`):")
            for s in stale:
                print(f"  - {s}")
            return 1
        print(f"OK: all {len(outputs)} generated files up to date.")
        return 0
    print(f"wrote {len(outputs)} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
